"""Initial migration

Revision ID: 0faff2bd379f
Revises: 
Create Date: 2025-03-13 15:23:30.312690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0faff2bd379f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('average_sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hashtag_text'), ['text'], unique=True)

    op.create_table('twitter_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('tweets_count', sa.Integer(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('twitter_created_at', sa.DateTime(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('sentiment_tendency', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('twitter_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_twitter_user_twitter_id'), ['twitter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_twitter_user_username'), ['username'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_tweets', sa.Integer(), nullable=True),
    sa.Column('filtered_tweets', sa.Integer(), nullable=True),
    sa.Column('max_tweets', sa.Integer(), nullable=True),
    sa.Column('timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('schedule_type', sa.String(length=20), nullable=True),
    sa.Column('schedule_value', sa.String(length=50), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mention', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mention_username'), ['username'], unique=True)

    op.create_table('collection_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('include_replies', sa.Boolean(), nullable=True),
    sa.Column('include_retweets', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_rule_collection_id'), ['collection_id'], unique=False)

    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twitter_id', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('twitter_created_at', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('retweets_count', sa.Integer(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('quotes_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('is_retweet', sa.Boolean(), nullable=True),
    sa.Column('is_quote', sa.Boolean(), nullable=True),
    sa.Column('is_reply', sa.Boolean(), nullable=True),
    sa.Column('original_tweet_id', sa.String(length=64), nullable=True),
    sa.Column('in_reply_to_tweet_id', sa.String(length=64), nullable=True),
    sa.Column('in_reply_to_user_id', sa.String(length=64), nullable=True),
    sa.Column('collection_method', sa.String(length=20), nullable=True),
    sa.Column('collection_query', sa.String(length=255), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('is_filtered', sa.Boolean(), nullable=True),
    sa.Column('filter_reason', sa.String(length=50), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_date', sa.DateTime(), nullable=True),
    sa.Column('has_media', sa.Boolean(), nullable=True),
    sa.Column('media_urls', sa.Text(), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('twitter_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['twitter_user_id'], ['twitter_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tweet_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_collection_method'), ['collection_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_in_reply_to_tweet_id'), ['in_reply_to_tweet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_in_reply_to_user_id'), ['in_reply_to_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_original_tweet_id'), ['original_tweet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_twitter_created_at'), ['twitter_created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_twitter_id'), ['twitter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tweet_twitter_user_id'), ['twitter_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tweet_user_id'), ['user_id'], unique=False)

    op.create_table('hashtag_tweet',
    sa.Column('hashtag_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('hashtag_id', 'tweet_id')
    )
    op.create_table('mention_tweet',
    sa.Column('mention_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mention_id'], ['mention.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('mention_id', 'tweet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mention_tweet')
    op.drop_table('hashtag_tweet')
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tweet_user_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_twitter_user_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_twitter_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_twitter_created_at'))
        batch_op.drop_index(batch_op.f('ix_tweet_original_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_language'))
        batch_op.drop_index(batch_op.f('ix_tweet_in_reply_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_in_reply_to_tweet_id'))
        batch_op.drop_index(batch_op.f('ix_tweet_collection_method'))
        batch_op.drop_index(batch_op.f('ix_tweet_collection_id'))

    op.drop_table('tweet')
    with op.batch_alter_table('collection_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_rule_collection_id'))

    op.drop_table('collection_rule')
    with op.batch_alter_table('mention', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mention_username'))

    op.drop_table('mention')
    op.drop_table('collection')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('twitter_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_twitter_user_username'))
        batch_op.drop_index(batch_op.f('ix_twitter_user_twitter_id'))

    op.drop_table('twitter_user')
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hashtag_text'))

    op.drop_table('hashtag')
    # ### end Alembic commands ###
