"""Initial migration.

Revision ID: 1c250347d9cd
Revises: 447966db9aa6
Create Date: 2025-03-15 09:00:38.848250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c250347d9cd'
down_revision = '447966db9aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment_analysis_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sentiment_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sentiment_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('engagement_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('virality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('has_ai_analysis', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('has_ai_analysis')
        batch_op.drop_column('virality_score')
        batch_op.drop_column('engagement_score')
        batch_op.drop_column('sentiment_details')
        batch_op.drop_column('sentiment_confidence')
        batch_op.drop_column('sentiment_analysis_method')

    # ### end Alembic commands ###
