"""Add processed_text field to Tweet model

Revision ID: 447966db9aa6
Revises: 703b7eac5bb2
Create Date: 2025-03-15 04:04:44.664175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447966db9aa6'
down_revision = '703b7eac5bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('processed_text')

    # ### end Alembic commands ###
